### ISSUE TITLE
patching doesnt appear to work

### ISSUE THREAD

**Issue by captainsawbones** [Erik-Debye/CattailsMods#1] opened 2022-05-12 15:17 UTC
Thank you for creating this.  When I follow the directions given, the patcher throws an error message that it can't find  part of the path ( steam\steamapps\common\cattails\speed increase\install speed increase mod\obj )  .  Is there something I'm doing incorrectly?

**Comment by Erik-Debye** [comment] 2022-05-12 23:31
Hey there, I haven't worked on this since my academic year started unfortunately. IIRC it worked perfectly then to install mods, but something may have changed. I just wanted to let you know that I will peek at this today and get back to you on it! Thank you for your message and I hope I can get back to you soon with some news.

**Comment by Erik-Debye** [comment] 2022-05-13 03:25
Alright, so the issue is with the HgPatcher tool and the use of GitHub to share mods. GitHub apparently strips all empty directories from uploads, which ended up breaking the Patcher Script. 

I went ahead and edited the script myself, which you can find here in my fork: [https://github.com/Erik-Debye/HgPatcher/tree/main/Scripts](https://github.com/Erik-Debye/HgPatcher/tree/main/Scripts) 

I also went ahead and created a pull request to the original repository as well. I am not a C# developer at all, so there may be bugs but I seem to have it working. Remember to always backup your original file before using a script on it.

Let me know how it goes! I will keep this issue open in the mean time.

**Comment by Erik-Debye** [comment] 2022-05-19 01:57
For now I will close this issue as solved, but feel free to open another one if there is still an issue with the new script.

**Closed as completed by Erik-Debye** 2022-05-19 01:57 UTC
